services:
  - type: web
    name: global-news
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: INGEST_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_API_KEY_2
        sync: false
      - key: GROQ_API_KEY_3
        sync: false
      - key: GROQ_API_KEY_4
        sync: false
      - key: GROQ_MODEL
        value: llama-3.3-70b-versatile
